jobs:
  verify:
    name: Action
    runs-on: ubuntu-20.04

    steps:
      - name: Pull Code
        uses: actions/checkout@v2
      - name: Download Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Run Tests
        run: ./run/build

name: Test

on:
  schedule:
    - cron: "55 0/3 * * *"
